/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_management;

/**
 *
 * @author Sarodh
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class delete extends javax.swing.JFrame {

    /**
     * Creates new form delete
     */
    public delete() {
        initComponents();
        
         //center the delete form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_deletecolor = new javax.swing.JPanel();
        jLabel_HEADDING = new javax.swing.JLabel();
        jLabel_itemcode = new javax.swing.JLabel();
        jLabel_itemname = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        resetB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        itemname = new javax.swing.JTextField();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        searchB = new javax.swing.JButton();
        jLabel_deletebck = new javax.swing.JLabel();
        oceanImage = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_deletecolor.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_deletecolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_HEADDING.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel_HEADDING.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HEADDING.setText("DELETE ITEM");

        javax.swing.GroupLayout jPanel_deletecolorLayout = new javax.swing.GroupLayout(jPanel_deletecolor);
        jPanel_deletecolor.setLayout(jPanel_deletecolorLayout);
        jPanel_deletecolorLayout.setHorizontalGroup(
            jPanel_deletecolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_deletecolorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_HEADDING)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_deletecolorLayout.setVerticalGroup(
            jPanel_deletecolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_deletecolorLayout.createSequentialGroup()
                .addComponent(jLabel_HEADDING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_deletecolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, 50));

        jLabel_itemcode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_itemcode.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_itemcode.setText("ENTER ITEM CODE");
        getContentPane().add(jLabel_itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 40));

        jLabel_itemname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_itemname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_itemname.setText("ITEM NAME");
        getContentPane().add(jLabel_itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, 30));

        itemcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcodeActionPerformed(evt);
            }
        });
        getContentPane().add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 190, 30));

        resetB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetB.setText("RESET");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        getContentPane().add(resetB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, 30));

        deleteB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteB.setForeground(new java.awt.Color(255, 0, 0));
        deleteB.setText("DELETE");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });
        getContentPane().add(deleteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 80, 30));

        itemname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameActionPerformed(evt);
            }
        });
        getContentPane().add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 190, 30));

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("  -");
        minimize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 30, 30));

        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 30, 30));

        searchB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchB.setText("SEARCH");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });
        getContentPane().add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel_deletebck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/img1.jpg"))); // NOI18N
        jLabel_deletebck.setText("jLabel1");
        getContentPane().add(jLabel_deletebck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 380));

        oceanImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/ocean image.jpg"))); // NOI18N
        oceanImage.setText("jLabel2");
        getContentPane().add(oceanImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcodeActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
        itemcode.setText("");
        itemname.setText("");
        
    }//GEN-LAST:event_resetBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        // TODO add your handling code here:
        
        if(verifyFields())
        {
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/food_management","root","");
            String s = "DELETE FROM `foods` WHERE food_id = ?";                       
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,itemcode.getText());
            int rs = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully deleted");
            
            itemcode.setText("");
            itemname.setText("");
            /*
            if(rs.next()==false)
                //itemname.setText(rs.getString("itemname"));
                
                JOptionPane.showMessageDialog(this, "Invalid Item Code. Try again");       
            
            else{
                
                itemname.setText((rs.getString("itemname")));
                //JOptionPane.showMessageDialog(this, "saved successfully");
            }*/
            
        }        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                   
        }        
       
    }//GEN-LAST:event_deleteBActionPerformed
    }
        
        
        
    private void itemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
            System.exit(0);

    }//GEN-LAST:event_closeMouseClicked

    
    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        minimize.setBorder(label_border);        
        minimize.setForeground(Color.black);
    }//GEN-LAST:event_minimizeMouseEntered

    
    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        minimize.setBorder(label_border);
        minimize.setForeground(Color.white);
        
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        close.setBorder(label_border);        
        close.setForeground(Color.black);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        close.setBorder(label_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        // TODO add your handling code here:
            
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/food_management","root","");
            String s = "SELECT food_name from foods where food_id = ?";           
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,itemcode.getText());
            ResultSet rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(this, "saved successfully");
            
            
            if(rs.next()==false)
                //itemname.setText(rs.getString("itemname"));
                
                JOptionPane.showMessageDialog(this, "Invalid Item Code. Try again");       
            
            else{
                
                itemname.setText((rs.getString("food_name")));
                //JOptionPane.showMessageDialog(this, "saved successfully");
            }          
        }        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                   
        }
    }//GEN-LAST:event_searchBActionPerformed
    
      public boolean verifyFields(){
        String icode = itemcode.getText();
        
        if(icode.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "One or More Fields are Empty!");
            return false;
        }
        else{
            return true;
        }
        
        
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JButton deleteB;
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_HEADDING;
    private javax.swing.JLabel jLabel_deletebck;
    private javax.swing.JLabel jLabel_itemcode;
    private javax.swing.JLabel jLabel_itemname;
    private javax.swing.JPanel jPanel_deletecolor;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel oceanImage;
    private javax.swing.JButton resetB;
    private javax.swing.JButton searchB;
    // End of variables declaration//GEN-END:variables
}
