/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_management;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.sql.*;


/**
 *
 * @author Sarodh
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
        
        //center the insert form
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1_inscolor = new javax.swing.JPanel();
        jLabel2_headding = new javax.swing.JLabel();
        jLabel_itemcode = new javax.swing.JLabel();
        jLabel_itemname = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        resetB = new javax.swing.JButton();
        insertB = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        iLabel_category = new javax.swing.JLabel();
        catogory = new javax.swing.JComboBox<>();
        jLabel1_bckimage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1_inscolor.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1_inscolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1_inscolor.setForeground(new java.awt.Color(204, 0, 51));

        jLabel2_headding.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_headding.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel2_headding.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_headding.setText("INSERT ITEMS");

        javax.swing.GroupLayout jPanel1_inscolorLayout = new javax.swing.GroupLayout(jPanel1_inscolor);
        jPanel1_inscolor.setLayout(jPanel1_inscolorLayout);
        jPanel1_inscolorLayout.setHorizontalGroup(
            jPanel1_inscolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_inscolorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2_headding, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1_inscolorLayout.setVerticalGroup(
            jPanel1_inscolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_inscolorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2_headding, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1_inscolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, -1));

        jLabel_itemcode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_itemcode.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_itemcode.setText("ITEM CODE");
        getContentPane().add(jLabel_itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 40));

        jLabel_itemname.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_itemname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_itemname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_itemname.setText("ITEM NAME");
        getContentPane().add(jLabel_itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        jLabel_price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_price.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_price.setText("PRICE");
        getContentPane().add(jLabel_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 40));

        itemcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcodeActionPerformed(evt);
            }
        });
        getContentPane().add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 260, 30));

        itemname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, 30));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 260, 30));

        resetB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetB.setText("RESET");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        getContentPane().add(resetB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 90, 30));

        insertB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertB.setText("INSERT");
        insertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBActionPerformed(evt);
            }
        });
        getContentPane().add(insertB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 90, 30));

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("  -");
        minimize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 30, 30));

        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 30, 30));

        iLabel_category.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iLabel_category.setForeground(new java.awt.Color(255, 255, 255));
        iLabel_category.setText("CATEGORY");
        getContentPane().add(iLabel_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 40));

        catogory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        catogory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Beverage", "Kottu", "Noodels", "Desserts", "Soup", "Seafood" }));
        catogory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catogoryActionPerformed(evt);
            }
        });
        getContentPane().add(catogory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 30));

        jLabel1_bckimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/img1.jpg"))); // NOI18N
        jLabel1_bckimage.setText("fsasfas");
        getContentPane().add(jLabel1_bckimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/ocean image.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcodeActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
        itemcode.setText("");
        itemname.setText("");
        price.setText("");
    }//GEN-LAST:event_resetBActionPerformed

    private void insertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBActionPerformed
        // TODO add your handling code here:
        
        /*
        PreparedStatement ps;
        ResultSet rs;                
        String s = "insert into testinsert(`itemcode`, `itemname`, `price`) VALUES (?,?,?)";
        
        
        try {
            ps = My_CNX.getConnection().prepareStatement(s);
            ps.setString(1,itemcode.getText());
            ps.setString(2, itemname.getText());
            ps.setString(3, price.getText());
            int rs = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved successfully");
             
            if(!rs.next()) {
                JOptionPane.showMessageDialog(this, "insert failed");
            } else
                JOptionPane.showMessageDialog(this, "saved successfully");
            
            
        } catch (Exception e) {
        }*/
        
       if(verifyFields())
       {
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/food_management","root","");
            String s =  "INSERT INTO `foods`(`food_id`, `food_name`, `price`, `category`) VALUES (?,?,?,?)";
            //String s =  "insert into foods(`food_id`, `food_name`, `price`) VALUES (?,?,?,?)";
            
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,itemcode.getText());
            ps.setString(2, itemname.getText());
            ps.setString(3, price.getText());
            String selectValue = catogory.getSelectedItem().toString();
            ps.setString(4,selectValue);
            
            
            int rs = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully saved");           
           
                    
            itemcode.setText("");
            itemname.setText("");
            price.setText("");
            
            /*
            if(rs.next())
                JOptionPane.showMessageDialog(this, "saved successfully");
            
            else{
                JOptionPane.showMessageDialog(this, "insert failed");
            }*/
            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                   
            }
        }
        
        
        
        
    }//GEN-LAST:event_insertBActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_closeMouseClicked

    
    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here
        
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        minimize.setBorder(label_border);        
        minimize.setForeground(Color.black);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        minimize.setBorder(label_border);
        minimize.setForeground(Color.white);
        
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        close.setBorder(label_border);        
        close.setForeground(Color.black);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        close.setBorder(label_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void catogoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catogoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catogoryActionPerformed
    
    
    //check empty fields
    public boolean verifyFields(){
        String icode = itemcode.getText();
        String iname = itemname.getText();
        String prc = price.getText();
        
        if(icode.trim().equals("")||iname.trim().equals("")
           ||prc.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "One or More Fields are Empty!");
            return false;
        }
        else{
            return true;
        }
        
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catogory;
    private javax.swing.JLabel close;
    private javax.swing.JLabel iLabel_category;
    private javax.swing.JButton insertB;
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemname;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1_bckimage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_headding;
    private javax.swing.JLabel jLabel_itemcode;
    private javax.swing.JLabel jLabel_itemname;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JPanel jPanel1_inscolor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField price;
    private javax.swing.JButton resetB;
    // End of variables declaration//GEN-END:variables
}
