/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_management;

/**
 *
 * @author Sarodh
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


public class modify extends javax.swing.JFrame {

    /**
     * Creates new form modify
     */
    public modify() {
        initComponents();
                
        //center the modify form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oceanImage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_headding = new javax.swing.JLabel();
        label_itemCode = new javax.swing.JLabel();
        label_itemName = new javax.swing.JLabel();
        label_price = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        itemname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        resetB = new javax.swing.JButton();
        modifyB = new javax.swing.JButton();
        jLabel_newname = new javax.swing.JLabel();
        jLabel_newprice = new javax.swing.JLabel();
        newname = new javax.swing.JTextField();
        newprice = new javax.swing.JTextField();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel_modifybck = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout oceanImageLayout = new javax.swing.GroupLayout(oceanImage);
        oceanImage.setLayout(oceanImageLayout);
        oceanImageLayout.setHorizontalGroup(
            oceanImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        oceanImageLayout.setVerticalGroup(
            oceanImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_headding.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel_headding.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_headding.setText("MODIFY ITEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_headding, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_headding, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 200, 60));

        label_itemCode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_itemCode.setForeground(new java.awt.Color(255, 255, 255));
        label_itemCode.setText("ENTER ITEM CODE");
        getContentPane().add(label_itemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 30));

        label_itemName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_itemName.setForeground(new java.awt.Color(255, 255, 255));
        label_itemName.setText("ITEM NAME");
        getContentPane().add(label_itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 30));

        label_price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_price.setForeground(new java.awt.Color(255, 255, 255));
        label_price.setText("PRICE");
        getContentPane().add(label_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 30));

        itemcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcodeActionPerformed(evt);
            }
        });
        getContentPane().add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 220, 30));

        searchB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchB.setText("SEARCH");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });
        getContentPane().add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 90, 30));

        itemname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameActionPerformed(evt);
            }
        });
        getContentPane().add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 30));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, 30));

        resetB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetB.setText("RESET");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        getContentPane().add(resetB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 80, 30));

        modifyB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modifyB.setText("MODIFY");
        modifyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBActionPerformed(evt);
            }
        });
        getContentPane().add(modifyB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, 30));

        jLabel_newname.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel_newname.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_newname.setText("NEW NAME");
        getContentPane().add(jLabel_newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 40));

        jLabel_newprice.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel_newprice.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_newprice.setText("NEW PRICE");
        getContentPane().add(jLabel_newprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 50));

        newname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnameActionPerformed(evt);
            }
        });
        getContentPane().add(newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 220, 30));

        newprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(newprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 220, 30));

        minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("  -");
        minimize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 30, 30));

        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 30));

        jLabel_modifybck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/img1.jpg"))); // NOI18N
        jLabel_modifybck.setText("jLabel1");
        getContentPane().add(jLabel_modifybck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/ocean image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcodeActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        // TODO add your handling code here:
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/food_management","root","");
            //String s = "SELECT itemname, price from testinsert where itemcode = ?";           
            String s =  "select food_name, price from foods where food_id =?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,itemcode.getText());
            ResultSet rs = ps.executeQuery();
            
            
            
            if(rs.next()==false)
                //itemname.setText(rs.getString("itemname"));
                
                JOptionPane.showMessageDialog(this, "Invalid Item Code. Try again");       
            
            else{
                
                itemname.setText((rs.getString("food_name")));
                price.setText((rs.getString("price")));
                //JOptionPane.showMessageDialog(this, "saved successfully");
            }
            
        }        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                   
        }
        
        
    }//GEN-LAST:event_searchBActionPerformed

    private void itemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBActionPerformed

    private void modifyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBActionPerformed
        // TODO add your handling code here:
        
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/food_management","root","");
            String s =  "UPDATE `foods` SET `food_name`=?,`price`=? WHERE food_id = ?";
            //String s =  "UPDATE `testinsert` SET `itemname`=[value-?],`price`=[value-?] WHERE itemcode = ?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,newname.getText());
            ps.setString(2, newprice.getText());
            ps.setString(3, itemcode.getText());
            
            
            int rs = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "successfully modified");           
           
                    
            itemcode.setText("");
            itemname.setText("");
            price.setText("");
            newname.setText("");
            newprice.setText("");
            
            /*
            if(rs.next())
                JOptionPane.showMessageDialog(this, "saved successfully");
            
            else{
                JOptionPane.showMessageDialog(this, "insert failed");
            }*/
            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                   
            }     
        
    }//GEN-LAST:event_modifyBActionPerformed
    
     public boolean  verifyFields()
        {
        String iname = newname.getText();
        String iprice = newprice.getText();       
        
        if(iname.trim().equals("")||iprice.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "One or More Fields are Empty!");
            return false;
        }
        else{
            return true;
        }
        }
    
    
    
    private void newnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newnameActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here
        System.exit(0);

    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        minimize.setBorder(label_border);        
        minimize.setForeground(Color.black);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        minimize.setBorder(label_border);
        minimize.setForeground(Color.white);
        
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black); 
        close.setBorder(label_border);        
        close.setForeground(Color.black);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white); 
        close.setBorder(label_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_headding;
    private javax.swing.JLabel jLabel_modifybck;
    private javax.swing.JLabel jLabel_newname;
    private javax.swing.JLabel jLabel_newprice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_itemCode;
    private javax.swing.JLabel label_itemName;
    private javax.swing.JLabel label_price;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton modifyB;
    private javax.swing.JTextField newname;
    private javax.swing.JTextField newprice;
    private javax.swing.JPanel oceanImage;
    private javax.swing.JTextField price;
    private javax.swing.JButton resetB;
    private javax.swing.JButton searchB;
    // End of variables declaration//GEN-END:variables
}
