/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_login;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author AdminSithum
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
        
        // center the  form
        this.setLocationRelativeTo(null);
        
        //Rounded corners
        //x & y cordinate values
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        
        
        //create a border to minimize & close
        //Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE)
                //jLabel_minimize.setBorder(border);
               
     
     
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize5 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Create_acc = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        user_icon = new javax.swing.JLabel();
        password_icon = new javax.swing.JLabel();
        User_login_Frame = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        Restaurant_img = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();

        minimize5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        minimize5.setForeground(new java.awt.Color(255, 255, 255));
        minimize5.setText(" -");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setText("User name");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 180, 30));

        Password.setText("jPasswordField1");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, 30));

        Create_acc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Create_acc.setForeground(new java.awt.Color(255, 255, 0));
        Create_acc.setText("No Account ? Create One");
        Create_acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Create_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Create_accMouseClicked(evt);
            }
        });
        getContentPane().add(Create_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 160, 20));

        Login.setBackground(new java.awt.Color(102, 204, 255));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        Reset.setBackground(new java.awt.Color(102, 204, 255));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-male-user-30.png"))); // NOI18N
        getContentPane().add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 30));

        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-password-30.png"))); // NOI18N
        getContentPane().add(password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        User_login_Frame.setForeground(new java.awt.Color(255, 255, 255));
        User_login_Frame.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "User Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Black", 1, 18), new java.awt.Color(51, 204, 255))); // NOI18N
        getContentPane().add(User_login_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 290, 310));

        jLabel_minimize.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 30, 20));

        Restaurant_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/pizza copysmall.jpg"))); // NOI18N
        Restaurant_img.setText("jLabel4");
        Restaurant_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        getContentPane().add(Restaurant_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 300));

        jLabel_Close.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Close.setText(" X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 30));

        background.setBackground(new java.awt.Color(51, 204, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/istockphoto-1212417063-612x612.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        minimize1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        minimize1.setForeground(new java.awt.Color(255, 255, 255));
        minimize1.setText(" -");
        getContentPane().add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
       try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db", "root", "");
        String s = "select * from users where username=? and password=?";
        PreparedStatement ps = con.prepareStatement(s);
        ps.setString(1, Username.getText());
        ps.setString(2, Password.getText());
        ResultSet rs = ps.executeQuery();
        
             if(rs.next())
                 
                 JOptionPane.showMessageDialog(this,"Login Succesfully");
             
             else 
                 
                  JOptionPane.showMessageDialog(this,"Login Failed");
             
        
        
        }catch(Exception e){
        
            System.out.println(e);
        
        }
        
        
        
    }//GEN-LAST:event_LoginActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
         Username.setText("");
        Password.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void Create_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Create_accMouseClicked
        // TODO add your handling code here:
        Login_Page rgf = new Login_Page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Create_accMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Create_acc;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Restaurant_img;
    private javax.swing.JLabel User_login_Frame;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel minimize1;
    private javax.swing.JLabel minimize5;
    private javax.swing.JLabel password_icon;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables
}
