/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_management;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        Border label_title_border = BorderFactory.createMatteBorder(1, 0, 1, 0, Color.white);
        jPanel1.setBorder(label_title_border);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_male);
        bg.add(jRadioButton_female);
        bg.add(jRadioButton_other);
        
        Border label_login_border = BorderFactory.createMatteBorder(0, 0, 1,0, Color.DARK_GRAY);
        jLabel1_login.setBorder(label_login_border);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_close.setBorder(label_border);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_firstname = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_lastname = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_pass1 = new javax.swing.JLabel();
        jLabel_pass2 = new javax.swing.JLabel();
        jLabel_phone = new javax.swing.JLabel();
        jLabe_gender = new javax.swing.JLabel();
        jLabel_add = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jTextField_lastname = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_pass1 = new javax.swing.JPasswordField();
        jPasswordField_pass2 = new javax.swing.JPasswordField();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_add = new javax.swing.JTextField();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jRadioButton_other = new javax.swing.JRadioButton();
        jButton_register = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jLabel1_login = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_title.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_title.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("Register Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 50));

        jLabel_firstname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_firstname.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_firstname.setText("First Name :");
        getContentPane().add(jLabel_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, -1));

        jLabel_minimize.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.setMaximumSize(new java.awt.Dimension(13, 22));
        jLabel_minimize.setMinimumSize(new java.awt.Dimension(13, 22));
        jLabel_minimize.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel_lastname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_lastname.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_lastname.setText("Last Name :");
        getContentPane().add(jLabel_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_username.setText("Username :");
        getContentPane().add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel_pass1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_pass1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_pass1.setText("Password :");
        getContentPane().add(jLabel_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, -1));

        jLabel_pass2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_pass2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_pass2.setText("Confirm Password :");
        getContentPane().add(jLabel_pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel_phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_phone.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_phone.setText("Phone :");
        getContentPane().add(jLabel_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabe_gender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabe_gender.setForeground(new java.awt.Color(204, 204, 255));
        jLabe_gender.setText(" Gender :");
        getContentPane().add(jLabe_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jLabel_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_add.setForeground(new java.awt.Color(204, 204, 255));
        jLabel_add.setText("Address :");
        getContentPane().add(jLabel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jTextField_firstname.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_firstnameFocusLost(evt);
            }
        });
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, 30));

        jTextField_lastname.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_lastnameFocusLost(evt);
            }
        });
        jTextField_lastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_lastnameMouseEntered(evt);
            }
        });
        getContentPane().add(jTextField_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, 30));

        jTextField_username.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 240, 30));

        jPasswordField_pass1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 240, 30));

        jPasswordField_pass2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField_pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 240, 30));

        jTextField_phone.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 240, 30));

        jTextField_add.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 240, 30));

        jRadioButton_male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_male.setForeground(new java.awt.Color(204, 255, 255));
        jRadioButton_male.setSelected(true);
        jRadioButton_male.setText("Male");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jRadioButton_female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_female.setForeground(new java.awt.Color(204, 255, 255));
        jRadioButton_female.setText("Female");
        jRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jRadioButton_other.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_other.setForeground(new java.awt.Color(204, 255, 255));
        jRadioButton_other.setText("Other");
        getContentPane().add(jRadioButton_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jButton_register.setBackground(new java.awt.Color(0, 153, 153));
        jButton_register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_register.setText("Register");
        jButton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_registerMouseExited(evt);
            }
        });
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 120, 40));

        jButton_reset.setBackground(new java.awt.Color(0, 153, 153));
        jButton_reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("Reset");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_resetMouseExited(evt);
            }
        });
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 110, 40));

        jLabel1_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1_login.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1_login.setText(">> Already Have an Account? Login");
        jLabel1_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1_loginMouseExited(evt);
            }
        });
        getContentPane().add(jLabel1_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, -1));

        jLabel_close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setText("  x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 30, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jTextField_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addActionPerformed

    private void jRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_femaleActionPerformed

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed

        String fname = jTextField_firstname.getText();
        String lname = jTextField_lastname.getText();
        String uname = jTextField_username.getText();
        String pass1 = jPasswordField_pass1.getText();
        String phone = jTextField_phone.getText();
        String address = jTextField_add.getText();
        String gender = "Male";
        
        if (jRadioButton_female.isSelected())
        {
            gender = "female";
        }else if(jRadioButton_other.isSelected()){
            gender = "other";
        }
        
        if (verifyFields()){
            if(!checkUsername(uname))
            {
                PreparedStatement ps;
                    ResultSet rs;
                    String registerUserQuery ="INSERT INTO `users`( `first_name`, `last_name`, `username`, `password`, `phone`, `address`, `gender`) VALUES (?,?,?,?,?,?,?)";
                
                try {
                                       
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, uname);
                    ps.setString(4, pass1);
                    ps.setString(5, phone);
                    ps.setString(6, address);
                    ps.setString(7, gender);
                   try {
                    
                        if (ps.executeUpdate() !=0){
                            JOptionPane.showMessageDialog(null, "Your Account Has Been Created ");
                        }
                        else {
                            JOptionPane.showMessageDialog(null,"Error: Check Your Information");
                        }
                        
                    } catch (Exception ex) {
                        Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }
    }//GEN-LAST:event_jButton_registerActionPerformed
    
     public boolean checkUsername(String username)
    {
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `users` WHERE `username`=?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if (rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken,Choose Another one","Username Failed",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
   
    private boolean verifyFields()
     {
        String fname = jTextField_firstname.getText();
        String lname = jTextField_lastname.getText();
        String uname = jTextField_username.getText();
        String phone = jTextField_phone.getText();
        String address = jTextField_add.getText();
        String pass1 = jPasswordField_pass1.getText();
        String pass2 = jPasswordField_pass2.getText();
        boolean x = false;
        if (fname.trim().equals("")||lname.trim().equals("")||uname.trim().equals("")||phone.trim().equals("")||address.trim().equals("")|| pass1.trim().equals("")|| pass2.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
        }
        //check if the two password are equals
        else if (!pass1.equals(pass2))
        {
            JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2);
            x= false;
        }
        //if everything is ok
        else{
            x = true;
        } 
        return x;
    } 
    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jTextField_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyTyped
        //allow only numbers 
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phoneKeyTyped

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        jTextField_add.setText("");
        jTextField_firstname.setText("");
        jTextField_lastname.setText("");
        jTextField_phone.setText("");
        jTextField_username.setText("");
        jPasswordField_pass1.setText("");
        jPasswordField_pass2.setText("");
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseEntered
        jButton_register.setBackground(new Color(0,101,130));
    }//GEN-LAST:event_jButton_registerMouseEntered

    private void jButton_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseExited
        jButton_register.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_jButton_registerMouseExited

    private void jButton_resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_resetMouseEntered
        jButton_reset.setBackground(new Color(0,101,130));
    }//GEN-LAST:event_jButton_resetMouseEntered

    private void jButton_resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_resetMouseExited
        jButton_reset.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_jButton_resetMouseExited

    private void jTextField_firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_firstnameFocusGained
        
    }//GEN-LAST:event_jTextField_firstnameFocusGained

    private void jTextField_firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_firstnameFocusLost

    }//GEN-LAST:event_jTextField_firstnameFocusLost

    private void jTextField_lastnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_lastnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameMouseEntered

    private void jTextField_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_lastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameFocusGained

    private void jTextField_lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_lastnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameFocusLost

    private void jLabel1_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_loginMouseClicked
        /*loginForm lf = new loginForm();

        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_jLabel1_loginMouseClicked

    private void jLabel1_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_loginMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1,0, new Color(153,153,255));
        jLabel1_login.setBorder(label_border);
    }//GEN-LAST:event_jLabel1_loginMouseEntered

    private void jLabel1_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_loginMouseExited
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1,0,  Color.darkGray);
        jLabel1_login.setBorder(label_border);
    }//GEN-LAST:event_jLabel1_loginMouseExited

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.YELLOW);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabe_gender;
    private javax.swing.JLabel jLabel1_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_add;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_firstname;
    private javax.swing.JLabel jLabel_lastname;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_pass1;
    private javax.swing.JLabel jLabel_pass2;
    private javax.swing.JLabel jLabel_phone;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_pass1;
    private javax.swing.JPasswordField jPasswordField_pass2;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JRadioButton jRadioButton_other;
    private javax.swing.JTextField jTextField_add;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables

    
}
